### ISSUE TITLE
Error searching in Add a new relation fields

### ISSUE THREAD

**Issue by advaircarvalho** [renatoalmeidaoliveira/nbservice#3]
When starting a search in the list fields of "Add a new relation fields" returns the following error

In the **Source** and **Destination** fields

<i class="mdi mdi-alert"></i> Server Error
</h5>
<div class="card-body">

<p>
There was a problem with your request. Please contact an administrator.
</p>

<hr />
<p>
The complete exception is provided below:
</p>
<pre class="block"><strong>&lt;class &#x27;AssertionError&#x27;&gt;</strong><br />
Expected parent FilterSet &#x27;nb_service.filters.ICFilter&#x27; to have a &#x27;.search()&#x27; method.

Python version: 3.8.10
NetBox version: 3.2.1</pre>
<p>
If further assistance is required, please post to the <a href="https://github.com/netbox-community/netbox/discussions">NetBox discussion forum</a> on GitHub.
</p>
<div class="text-end">
<a href="/" class="btn btn-primary">Home Page</a>
</div>
</div>
</div>
</div>
</div>
</div>
</body>

</html>

**Comment by renatoalmeidaoliveira** [comment]
Hello  @advaircarvalho thank you for your report..
There was a problem in the ICFilter implementation, that was fixed in   [commit](https://github.com/renatoalmeidaoliveira/nbservice/commit/1163e30bc2a73440c07e80f116c1da759fb9f843).
Please update your plugin with:
pip install --upgrade nb-service
And it the problem persists please let me know.

**Comment by advaircarvalho** [comment]
I did the procedure and now it's working. Thanks
